### PR TITLE
Issue 60 

### PR DESCRIPTION
**Pull request by katehausladen**
this branch added functionality to get the gpp string (issue #60)

some sites that have gpp for testing: [sites_w_gpp.xlsx](https://github.com/privacy-tech-lab/gpc-web-crawler/files/12795066/sites_w_gpp.xlsx)

### CODE REVIEW

**Comment by katehausladen** [comment]
The command to create the sql table is: `CREATE TABLE entries (id INTEGER PRIMARY KEY AUTO_INCREMENT, site_id INTEGER, domain varchar(255), dns_link BOOLEAN, sent_gpc BOOLEAN, uspapi_before_gpc varchar(255), uspapi_after_gpc varchar(255), usp_cookies_before_gpc varchar(255), usp_cookies_after_gpc varchar(255), OptanonConsent_before_gpc varchar(800), OptanonConsent_after_gpc varchar(800), gpp_before_gpc varchar(4000), gpp_after_gpc varchar(4000));`

**Comment by SebastianZimmeck** [comment]
> The command to create the sql table is

Great! @katehausladen, can you put that into the readme? Maybe, a new section or under a current one. "The crawler relies on a database ... This is how you set it up ... ."

**Comment by katehausladen** [comment]
Yes, I'll update the wiki once this gets merged

**Comment by OliverWang13** [comment]
Everything looks good on my end, I'll go ahead and merge

**Pull request merged**
